site_fullname:          "scrabble"
site_name:              "scrabble.lv"
host:                   "scrabble.lv"
host_nice:              "scrabble.lv"
email_from:             "scrabble <info@scrabble.lv>"
locales:
  - lv

facebook:
  key:      <%= ENV['SCRABBLE_LV_FACEBOOK_KEY'] %>
  secret:   <%= ENV['SCRABBLE_LV_FACEBOOK_SECRET'] %>
