site_fullname:          "Scrabble"
site_name:              "Scrabble.lv"
host:                   "Scrabble.lv"
host_nice:              "Scrabble.lv"
email_from:             "Scrabble <info@scrabble>"
rpp:                    20
locales:
  - lv

ga_account:             "UA-xxxxxx-1"


facebook:
  key:      "282544095144850"
  secret:   "7733523886d90f7996c4b84cadb6b3af"