site_fullname:          "Scrab"
site_name:              "Scrab.us"
host:                   "Scrab.us"
host_nice:              "Scrab.us"
email_from:             "Scrab <info@scrab.us>"
rpp:                    20
locales:
  - lv

ga_account:             "UA-xxxxxx-1"

facebook:
  key:      "109360432579933"
  secret:   "b28bf2bd4c605eb2fc0aed756a2e24c6"