site_fullname:          "Scrab"
site_name:              "Scrab.us"
host:                   "Scrab.us"
host_nice:              "Scrab.us"
email_from:             "Scrab <info@scrab.us>"
rpp:                    20
locales:
  - lv

ga_account:             "UA-xxxxxx-1"

facebook:
  key:      "282544095144850"
  secret:   "7733523886d90f7996c4b84cadb6b3af"