development: &dev
  adapter: mysql2
  encoding: utf8
  database: scrabble_dev
  username: scrabble_dev 
  password: bvAETBM4ayhRG5sJ
  host: localhost

demo:
  <<: *dev

test:
  adapter: mysql2
  encoding: utf8
  database: scrabble_test
  username: scrabble_test
  password: bvAETBM4ayhRG5sJ
  host: localhost
  
production:
  adapter: mysql2
  encoding: utf8
  database: scrabble
  username: scrabble
  password: bvAETBM4ayhRG5sJ
  host: localhost