development: &common
  adapter: mysql2
  encoding: utf8
  database: scrabble
  username: scrabble
  password: bvAETBM4ayhRG5sJ
  host: localhost

test:
  <<: *common
  database: scrabble_test
  username: scrabble_test

production:
  <<: *common
